### ISSUE TITLE
Credit Card Payment creates one 'Invalid' payment and one 'Completed' payment.

### ISSUE THREAD

**Issue by robbie-mcfarlane** [komoju/spree_komoju#36]
When a customer checks out using a credit card and confirms their order, two payments seem to be created in Spree; one 'Invalid' and one 'Completed'.

**Comment by robbie-mcfarlane** [comment]
I must add, this happens when entering a New credit card and using an Existing card.

**Comment by shioyama** [comment]
This is apparently a spree issue, not a spree_komoju issue: https://github.com/spree/spree/issues/6499

I'm guessing upgrading to 3.1.0.beta should fix it.
