### ISSUE TITLE
NoMethodError in Spree::Admin::RefundsController#create undefined method `credit' for #<ActiveMerchant::Billing::KomojuGateway:0x007fca9bd61bc8>

### ISSUE THREAD

**Issue by robbie-mcfarlane** [komoju/spree_komoju#38]
When trying to refund a payment in the admin backend to following error is raised:

NoMethodError in Spree::Admin::RefundsController#create undefined method `credit' for #<ActiveMerchant::Billing::KomojuGateway:0x007fca9bd61bc8>

**Comment by shioyama** [comment]
We've just released 0.0.7, this should be fixed now.

**Comment by robbie-mcfarlane** [comment]
Thank you so much guys! Will update now :)
