### ISSUE TITLE
(question)Is this support solidus?

### ISSUE THREAD

**Issue by k-kawa** [komoju/spree_komoju#48]
Hi, there.

I'm interested in using this gem with Solidus but it seems to work only with Spree whose source code is going to be closed (I'm not sure the detail)...

Is there any plan to support Solidus or another gem forked from this?
or should we use Spree?

**Comment by rramsden** [comment]
Hi @k-kawa,

We're looking at adding support for Solidus v1.2.2 now
We have a WIP pull request open (see https://github.com/komoju/spree_komoju/pull/49)

I'll let you know once we've finished :-)

**Comment by k-kawa** [comment]
What a quick response with pull request!!
Thank you, @rramsden 

btw, are you a developer inside Komoju?
I made an account today and found it cool and easy to get started!

**Comment by rramsden** [comment]
Yes I work for Komoju. Thanks for the feedback! :smile:

**Comment by k-kawa** [comment]
:+1:
